Month 10/step 1
boolishta/react-burger pull request #10
Opened 2023-07-05 07:58 UTC by boolishta

2023-07-06 09:51 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали **очень хорошую** работу по типизации вашего проекта, не применялся `ts-ignore`, аккуратно описаны типы, **так держать**👍

- Следует улучшить типизацию функции `checkResponse`, добавив ей возможность возвращать конкретный тип, вместо `any` (подробнее в комментариях);
- Использование типа `any` в большинстве случае **нецелесообразно**, т.к. этот подход не позволяет анализатору кода своевременно проверять его на ошибки, которые могут быть выявлены на этапе сборки проекта и усложняет вашу работу с кодом, т.к. значения будут неочевидными (см. https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any). Типизация связанная с Redux сейчас не учитывается.

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---


**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-07-06 09:51 UTC, randomroot commented on src/utils/burger-api.ts
> +const checkReponse = (res: Response) => {
🔴 **Нужно исправить:**

В текущем виде функция `onResponse` не конкретизирует тип возвращаемого значения в теле ответа, поэтому все последующие функции связанные с ней работают с `any`, что не позволяет TypeScript отследить корректность вашего кода.

**Чтобы улучшить данную ситуацию** вы можете воспользоваться следующим подходом:

На основе всех ответов из API вашего бэкенда вы можете обратить внимание, что они имеют схожую структуру с полем `success`, поэтому воспользовавшись пересечением типов получим универсальную структуру:

```typescript
type TResponse<T> = {
  success: boolean;
} & T;
```

где `T` - тип, в котором описаны остальные ключи запроса, например `{ accessToken: string, refreshToken: string }`, которую можно использовать в функции проверки успешности и вернуть назад конкретный тип, в случае успеха:

```typescript
const checkResponse = <T>(res: Response) => {
  return res.ok ? res.json().then(data => data as TResponse<T>) : Promise.reject(res.status);
};
```
А затем применить её на ваши методы, связанные с вызовом API, создав для каждого из них (за исключением схожих) типы результатов и передав эти типы в функцию `checkResponse`. И тогда в других функциях, где будут вызывать данные методы вы получите правильный тип и валидацию вашего кода:

![image](https://user-images.githubusercontent.com/15111821/222458869-af3604af-61f4-478d-8d5a-fd369865f663.png)

2023-07-06 09:51 UTC, randomroot commented on src/components/burger-constructor-element/burger-constructor-element.tsx
> +  ingredient: IIngredient & { uuid: string };
🟡 **Можно улучшить:**

Имеет смысл вынести данный тип, чтобы потом его переиспользовать например в сторе

2023-07-06 09:51 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.tsx
> +            onClick={() => null}
🟡 **Можно улучшить:**

Имеет смысл добавить перелистывание к нужной категории по нажатию на таб

2023-07-06 09:51 UTC, randomroot commented on src/components/ingredient-image/ingredient-image.tsx
> +        alt=""
🟡 **Можно улучшить:**

В качестве альтернативного текста лучше использовать наименование ингредиента

2023-07-06 09:51 UTC, randomroot commented on src/components/orders-history/orders-history.tsx
>              ingredients.find((ingredient) => ingredient._id === id)
🟡 **Можно улучшить:**

Обратите внимание, что в случае, если нужный ингредиент не будет найден в исходном списке (например убрали ингредиент из нашего меню, но мы смотрим старый заказ), то в результат попадёт `null`

2023-07-06 09:51 UTC, randomroot commented on src/pages/feed/feed.tsx
> +      orders.map((order: any) => {
🔴 **Нужно исправить:** 

Следует задать конкретный тип для параметра `order` вместо `any`

2023-07-06 09:51 UTC, randomroot commented on src/pages/feed/feed.tsx
> +    const normalizeOrders: any = (orders: TWsOrder[]) =>
Следует задать конкретный возвращаемый тип для результата функции вместо `any`

2023-07-09 09:22 UTC, randomroot requested changes
**Здравствуйте!**

Вы **успешно** внесли изменения и улучшения в ваш проект, так держать, однако остался момент, который следует также **исправить** для сдачи проекта в данном спринте:

- Следует удалить возвращаемый тип из функций API, который содержит `any`: `Promise<any>`, т.к. теперь функция `checkResponse` возвращает конкретный результат'

**Хорошего вам дня и настроения!** 🐈

2023-07-09 09:22 UTC, randomroot commented on src/utils/burger-api.ts
> +export function loadIngredients(): Promise<any> {
🔴 **Нужно исправить:**

Здесь и ниже: следует удалить возвращаемый тип, который содержит `any`: `Promise<any>`, т.к. теперь функция `checkResponse` возвращает конкретный результат

2023-07-10 12:50 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-07-19 06:40 UTC, boolishta commented
@randomroot добавил типизацию редакса, можешь посмотреть?

2023-07-19 10:02 UTC, randomroot commented
@boolishta да, в течение дня сегодня проверю 👍

2023-07-19 18:54 UTC, randomroot approved these changes
Работа по типизации Редакса проделана **очень аккуратно**, критических замечаний нет, но оставил два комментария - ознакомьтесь с ними и проведите необходимые изменения. После этого ваш PR **можно** сливать без дополнительно подтверждения.

**Хорошего вам дня!** 🐈

2023-07-19 18:54 UTC, randomroot commented on src/services/actions/ws.ts
> +        token: token.slice('Bearer'.length).trim(),
Обратите внимание, что если токена не будет, то будет ошибка, лучше проверить его наличие

2023-07-19 18:54 UTC, randomroot commented on src/services/actions/order.ts
> +    order: any;
Следует указать конкретную типизацию для заказа

2023-07-20 06:23 UTC, merged